package skyfall.section2week4;

import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class BeanDefinitionTest {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext ac = new AnnotationConfigApplicationContext(DependencyConfig.class);
        String[] beanDefinitionNames = ac.getBeanDefinitionNames();

        for (String beanDefinitionName : beanDefinitionNames) {
            BeanDefinition beanDefinition = ac.getBeanDefinition(beanDefinitionName);
            if (beanDefinition.getRole() == BeanDefinition.ROLE_APPLICATION) {
                System.out.printf("beanDefinitionName : %s, " +
                        "beanDefinition : %s\n",beanDefinitionName,beanDefinition);
            }
        }
    }
}
//beanDefinitionName : dependencyConfig, beanDefinition : Generic bean: class [skyfall.section2week4.DependencyConfig]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : section2Week4Application, beanDefinition : Generic bean: class [skyfall.section2week4.Section2Week4Application$$EnhancerBySpringCGLIB$$a9ddaad3]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\keddy\Desktop\Personal Project\Spring\section2-week4\build\classes\java\main\skyfall\section2week4\Section2Week4Application.class]
//beanDefinitionName : coffeeRepository, beanDefinition : Generic bean: class [skyfall.section2week4.coffee.CoffeeRepository]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\keddy\Desktop\Personal Project\Spring\section2-week4\build\classes\java\main\skyfall\section2week4\coffee\CoffeeRepository.class]
//beanDefinitionName : coffeeService, beanDefinition : Generic bean: class [skyfall.section2week4.coffee.CoffeeService]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\keddy\Desktop\Personal Project\Spring\section2-week4\build\classes\java\main\skyfall\section2week4\coffee\CoffeeService.class]
//beanDefinitionName : memberRepository, beanDefinition : Generic bean: class [skyfall.section2week4.member.MemberRepository]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\keddy\Desktop\Personal Project\Spring\section2-week4\build\classes\java\main\skyfall\section2week4\member\MemberRepository.class]
//beanDefinitionName : memberService, beanDefinition : Generic bean: class [skyfall.section2week4.member.MemberService]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\keddy\Desktop\Personal Project\Spring\section2-week4\build\classes\java\main\skyfall\section2week4\member\MemberService.class]
//beanDefinitionName : org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : propertySourcesPlaceholderConfigurer, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=propertySourcesPlaceholderConfigurer; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/context/PropertyPlaceholderAutoConfiguration.class]
//beanDefinitionName : org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : forceAutoProxyCreatorToUseClassProxying, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=forceAutoProxyCreatorToUseClassProxying; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/aop/AopAutoConfiguration$ClassProxyingConfiguration.class]
//beanDefinitionName : org.springframework.boot.autoconfigure.aop.AopAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.aop.AopAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : applicationAvailability, beanDefinition : Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration; factoryMethodName=applicationAvailability; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/availability/ApplicationAvailabilityAutoConfiguration.class]
//beanDefinitionName : org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : lifecycleProcessor, beanDefinition : Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration; factoryMethodName=defaultLifecycleProcessor; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/context/LifecycleAutoConfiguration.class]
//beanDefinitionName : spring.lifecycle-org.springframework.boot.autoconfigure.context.LifecycleProperties, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.context.LifecycleProperties]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.info.ProjectInfoProperties]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : spring.sql.init-org.springframework.boot.autoconfigure.sql.init.SqlInitializationProperties, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.sql.init.SqlInitializationProperties]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor, beanDefinition : Root bean: class [org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : taskExecutorBuilder, beanDefinition : Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration; factoryMethodName=taskExecutorBuilder; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class]
//beanDefinitionName : applicationTaskExecutor, beanDefinition : Root bean: class [null]; scope=; abstract=false; lazyInit=true; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration; factoryMethodName=applicationTaskExecutor; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class]
//beanDefinitionName : spring.task.execution-org.springframework.boot.autoconfigure.task.TaskExecutionProperties, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.task.TaskExecutionProperties]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration, beanDefinition : Generic bean: class [org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
//beanDefinitionName : taskSchedulerBuilder, beanDefinition : Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration; factoryMethodName=taskSchedulerBuilder; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/task/TaskSchedulingAutoConfiguration.class]
//beanDefinitionName : spring.task.scheduling-org.springframework.boot.autoconfigure.task.TaskSchedulingProperties, beanDefinition : Root bean: class [org.springframework.boot.autoconfigure.task.TaskSchedulingProperties]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null